include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Dart Style Rules
    prefer_single_quotes: true
    prefer_relative_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Error Rules
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Style Rules
    camel_case_types: true
    library_names: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"